name: Run Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Start Next.js server
        run: npm run start &
        env:
          PORT: 3000

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress Tests
        run: npx cypress run
